#!/usr/bin/env bash
# config.sh - Configuration and constants for system-tools

# Cache and temp thresholds (in bytes)
CACHE_WARN_THRESHOLD=$((1073741824))          # 1 GB
USER_CACHE_WARN_THRESHOLD=$((3221225472))    # 3 GB
TMP_WARN_THRESHOLD=$((1073741824))            # 1 GB
LARGE_FILE_THRESHOLD=$((524288000))           # 500 MB

# Cleanliness score penalties
SCORE_CACHE_PENALTY=10
SCORE_USER_CACHE_PENALTY=15
SCORE_TMP_PENALTY=10
SCORE_ORPHANED_PENALTY=5
SCORE_UPDATES_PENALTY=10
SCORE_UPDATE_THRESHOLD=5

# Cleanliness score thresholds
SCORE_EXCELLENT=85
SCORE_GOOD=70
SCORE_FAIR=50

# Directory paths
TARGET_INSTALL_DIR="${HOME}/.local/bin"
CONFIG_FILE="${HOME}/.system-tools-repo"
DEFAULT_SHELL_RC="${HOME}/.bashrc"
ALT_SHELL_RC="${HOME}/.zshrc"

# Repository settings
REPO_DEFAULT_BRANCH="main"
REPO_REMOTE="origin"

# Monitor settings
MONITOR_REFRESH_INTERVAL=2

# Enabled features (can be disabled on systems without support)
ENABLE_FIRMWARE_UPDATES=true

export CACHE_WARN_THRESHOLD USER_CACHE_WARN_THRESHOLD TMP_WARN_THRESHOLD LARGE_FILE_THRESHOLD
export SCORE_CACHE_PENALTY SCORE_USER_CACHE_PENALTY SCORE_TMP_PENALTY SCORE_ORPHANED_PENALTY
export SCORE_UPDATES_PENALTY SCORE_UPDATE_THRESHOLD SCORE_EXCELLENT SCORE_GOOD SCORE_FAIR
export TARGET_INSTALL_DIR CONFIG_FILE DEFAULT_SHELL_RC ALT_SHELL_RC
export REPO_DEFAULT_BRANCH REPO_REMOTE MONITOR_REFRESH_INTERVAL ENABLE_FIRMWARE_UPDATES
